// apps/demo-vue/src/components/PostCardTab.vue
<template>
  <div class="space-y-6">
    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Card Variant</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Default card with author avatar, title, content preview, and stats.
      </p>
      <div class="max-w-lg space-y-4">
        <HivePostCard
          author="barddev"
          permlink="my-honey-pot"
        />
        <HivePostCard
          :author="GTG_POST_A.author"
          :permlink="GTG_POST_A.permlink"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Compact Variant</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Inline row with thumbnail, title, and stats. Suitable for lists.
      </p>
      <div class="space-y-3 max-w-lg">
        <HivePostCard
          v-for="post in DEMO_POSTS"
          :key="post.permlink"
          :author="post.author"
          :permlink="post.permlink"
          variant="compact"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Grid Variant</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Card optimized for grid layouts with prominent thumbnail.
      </p>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <HivePostCard
          v-for="post in DEMO_POSTS"
          :key="post.permlink"
          :author="post.author"
          :permlink="post.permlink"
          variant="grid"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Hidden Elements</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Use the hide prop to selectively remove author info and thumbnail.
      </p>
      <div class="max-w-lg">
        <HivePostCard
          author="barddev"
          permlink="my-honey-pot"
          :hide="['author', 'thumbnail']"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Custom Link Target</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Override the default link base URL with linkTarget prop. Links will
        point to PeakD instead of the default OpenHive blog.
      </p>
      <div class="max-w-lg">
        <HivePostCard
          author="blocktrades"
          permlink="updates-for-hive-roadmap-from-the-blocktrades-team"
          link-target="https://peakd.com"
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { HivePostCard } from "@kkocot/honeycomb-vue";

const BARDDEV_POST = { author: "barddev", permlink: "my-honey-pot" };
const BLOCKTRADES_POST = {
  author: "blocktrades",
  permlink: "updates-for-hive-roadmap-from-the-blocktrades-team",
};
const GTG_POST_A = {
  author: "gtg",
  permlink: "hive-hardfork-28-jump-starter-kit",
};
const GTG_POST_B = {
  author: "gtg",
  permlink: "brace-yourself-hardfork-is-coming",
};

const DEMO_POSTS = [BARDDEV_POST, BLOCKTRADES_POST, GTG_POST_A, GTG_POST_B];
</script>

// apps/demo-react/components/PostCardTab.tsx
"use client";

import { HivePostCard } from "@kkocot/honeycomb-react";

const BARDDEV_POST = "my-honey-pot";
const BLOCKTRADES_POST =
  "updates-for-hive-roadmap-from-the-blocktrades-team";
const GTG_POST_A = "hive-hardfork-28-jump-starter-kit";
const GTG_POST_B = "brace-yourself-hardfork-is-coming";

export default function PostCardTab() {
  return (
    <div className="space-y-6">
      <section className="border border-border rounded-lg p-6 bg-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Card Variant</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Default variant with author info, body preview, and post stats.
        </p>
        <div className="max-w-lg space-y-4">
          <HivePostCard author="barddev" permlink={BARDDEV_POST} />
          <HivePostCard author="gtg" permlink={GTG_POST_A} />
        </div>
      </section>

      <section className="border border-border rounded-lg p-6 bg-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Compact Variant</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Condensed layout ideal for post lists and sidebars.
        </p>
        <div className="max-w-lg space-y-3">
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            variant="compact"
          />
          <HivePostCard
            author="blocktrades"
            permlink={BLOCKTRADES_POST}
            variant="compact"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_A}
            variant="compact"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_B}
            variant="compact"
          />
        </div>
      </section>

      <section className="border border-border rounded-lg p-6 bg-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Grid Variant</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Thumbnail-first layout for image galleries and grid views.
        </p>
        <div className="grid grid-cols-2 gap-4 max-w-2xl">
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            variant="grid"
          />
          <HivePostCard
            author="blocktrades"
            permlink={BLOCKTRADES_POST}
            variant="grid"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_A}
            variant="grid"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_B}
            variant="grid"
          />
        </div>
      </section>

      <section className="border border-border rounded-lg p-6 bg-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Hidden Elements</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Hide specific parts of the post card using the hide prop.
        </p>
        <div className="max-w-lg space-y-4">
          <div>
            <p className="text-xs text-muted-foreground mb-2">
              hide={`["author", "thumbnail"]`}
            </p>
            <HivePostCard
              author="barddev"
              permlink={BARDDEV_POST}
              hide={["author", "thumbnail"]}
            />
          </div>
          <div>
            <p className="text-xs text-muted-foreground mb-2">
              hide={`["payout", "votes", "comments"]`}
            </p>
            <HivePostCard
              author="barddev"
              permlink={BARDDEV_POST}
              hide={["payout", "votes", "comments"]}
            />
          </div>
        </div>
      </section>

      <section className="border border-border rounded-lg p-6 bg-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Custom Link Target</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Links point to different Hive frontends.
        </p>
        <div className="max-w-lg space-y-3">
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            linkTarget="https://peakd.com"
            variant="compact"
          />
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            linkTarget="https://ecency.com"
            variant="compact"
          />
        </div>
      </section>
    </div>
  );
}
