// apps/demo-svelte-kit/src/lib/components/ApiTrackerTab.svelte
<script lang="ts">
  import { ApiTracker } from "@hiveio/honeycomb-svelte";
</script>

<div class="space-y-6">
  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">API Tracker</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Click the tracker to see all API endpoints and their health status.
    </p>
    <ApiTracker />
  </section>
</div>

// apps/demo-react-vite/src/components/ApiTrackerTab.tsx
import { ApiTracker } from "@hiveio/honeycomb-react";

export default function ApiTrackerTab() {
  return (
    <div className="space-y-6">
      <section className="border border-hive-border rounded-lg p-6 bg-hive-muted/20">
        <h2 className="text-2xl font-semibold mb-4">API Tracker</h2>
        <p className="text-sm text-hive-muted-foreground mb-4">
          Click the tracker to see all API endpoints and their health status.
        </p>
        <ApiTracker />
      </section>
    </div>
  );
}
