// apps/demo-react-next/components/PostCardTab.tsx
"use client";

import { HivePostCard } from "@hiveio/honeycomb-react";

const BARDDEV_POST = "my-honey-pot";
const BLOCKTRADES_POST =
  "updates-for-hive-roadmap-from-the-blocktrades-team";
const GTG_POST_A = "hive-hardfork-28-jump-starter-kit";
const GTG_POST_B = "brace-yourself-hardfork-is-coming";

export default function PostCardTab() {
  return (
    <div className="space-y-6">
      <section className="border border-hive-border rounded-lg p-6 bg-hive-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Card Variant</h2>
        <p className="text-sm text-hive-muted-foreground mb-4">
          Default variant with author info, body preview, and post stats.
        </p>
        <div className="max-w-lg space-y-4">
          <HivePostCard author="barddev" permlink={BARDDEV_POST} />
          <HivePostCard author="gtg" permlink={GTG_POST_A} />
        </div>
      </section>

      <section className="border border-hive-border rounded-lg p-6 bg-hive-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Compact Variant</h2>
        <p className="text-sm text-hive-muted-foreground mb-4">
          Condensed layout ideal for post lists and sidebars.
        </p>
        <div className="max-w-lg space-y-3">
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            variant="compact"
          />
          <HivePostCard
            author="blocktrades"
            permlink={BLOCKTRADES_POST}
            variant="compact"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_A}
            variant="compact"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_B}
            variant="compact"
          />
        </div>
      </section>

      <section className="border border-hive-border rounded-lg p-6 bg-hive-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Grid Variant</h2>
        <p className="text-sm text-hive-muted-foreground mb-4">
          Thumbnail-first layout for image galleries and grid views.
        </p>
        <div className="grid grid-cols-2 gap-4 max-w-2xl">
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            variant="grid"
          />
          <HivePostCard
            author="blocktrades"
            permlink={BLOCKTRADES_POST}
            variant="grid"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_A}
            variant="grid"
          />
          <HivePostCard
            author="gtg"
            permlink={GTG_POST_B}
            variant="grid"
          />
        </div>
      </section>

      <section className="border border-hive-border rounded-lg p-6 bg-hive-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Hidden Elements</h2>
        <p className="text-sm text-hive-muted-foreground mb-4">
          Hide specific parts of the post card using the hide prop.
        </p>
        <div className="max-w-lg space-y-4">
          <div>
            <p className="text-xs text-hive-muted-foreground mb-2">
              hide={`["author", "thumbnail"]`}
            </p>
            <HivePostCard
              author="barddev"
              permlink={BARDDEV_POST}
              hide={["author", "thumbnail"]}
            />
          </div>
          <div>
            <p className="text-xs text-hive-muted-foreground mb-2">
              hide={`["payout", "votes", "comments"]`}
            </p>
            <HivePostCard
              author="barddev"
              permlink={BARDDEV_POST}
              hide={["payout", "votes", "comments"]}
            />
          </div>
        </div>
      </section>

      <section className="border border-hive-border rounded-lg p-6 bg-hive-muted/20">
        <h2 className="text-2xl font-semibold mb-2">Custom Link Target</h2>
        <p className="text-sm text-hive-muted-foreground mb-4">
          Links point to different Hive frontends.
        </p>
        <div className="max-w-lg space-y-3">
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            linkTarget="https://peakd.com"
            variant="compact"
          />
          <HivePostCard
            author="barddev"
            permlink={BARDDEV_POST}
            linkTarget="https://ecency.com"
            variant="compact"
          />
        </div>
      </section>
    </div>
  );
}

// apps/demo-svelte-vite/src/components/PostCardTab.svelte
<script lang="ts">
  import { HivePostCard } from "@hiveio/honeycomb-svelte";
  import type { PostHideOption } from "@hiveio/honeycomb-svelte";

  const POST_A = { author: "barddev", permlink: "my-honey-pot" };
  const POST_B = {
    author: "blocktrades",
    permlink: "updates-for-hive-roadmap-from-the-blocktrades-team",
  };
  const POST_C = {
    author: "gtg",
    permlink: "hive-hardfork-28-jump-starter-kit",
  };
  const POST_D = {
    author: "gtg",
    permlink: "brace-yourself-hardfork-is-coming",
  };

  const HIDDEN_ELEMENTS: PostHideOption[] = ["payout", "votes"];
</script>

<div class="space-y-6">
  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Card Variant</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Default full card with thumbnail, author, title, body preview, and stats.
    </p>
    <div class="max-w-lg space-y-4">
      <HivePostCard author={POST_A.author} permlink={POST_A.permlink} />
      <HivePostCard author={POST_C.author} permlink={POST_C.permlink} />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Compact Variant</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Inline layout with small thumbnail, title, and stats. Good for lists and
      sidebars.
    </p>
    <div class="max-w-lg space-y-3">
      <HivePostCard
        author={POST_A.author}
        permlink={POST_A.permlink}
        variant="compact"
      />
      <HivePostCard
        author={POST_B.author}
        permlink={POST_B.permlink}
        variant="compact"
      />
      <HivePostCard
        author={POST_C.author}
        permlink={POST_C.permlink}
        variant="compact"
      />
      <HivePostCard
        author={POST_D.author}
        permlink={POST_D.permlink}
        variant="compact"
      />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Grid Variant</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Image-first layout designed for grid displays and content feeds.
    </p>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <HivePostCard
        author={POST_A.author}
        permlink={POST_A.permlink}
        variant="grid"
      />
      <HivePostCard
        author={POST_B.author}
        permlink={POST_B.permlink}
        variant="grid"
      />
      <HivePostCard
        author={POST_C.author}
        permlink={POST_C.permlink}
        variant="grid"
      />
      <HivePostCard
        author={POST_D.author}
        permlink={POST_D.permlink}
        variant="grid"
      />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Hidden Elements</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Use the <code class="text-xs bg-muted px-1 py-0.5 rounded">hide</code>
      prop to selectively remove payout, votes, comments, author, thumbnail, or time.
    </p>
    <div class="max-w-lg">
      <HivePostCard
        author={POST_A.author}
        permlink={POST_A.permlink}
        hide={HIDDEN_ELEMENTS}
      />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Custom Link Target</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Override the default link base URL with
      <code class="text-xs bg-muted px-1 py-0.5 rounded">linkTarget</code>.
      Links below point to peakd.com.
    </p>
    <div class="max-w-lg">
      <HivePostCard
        author={POST_B.author}
        permlink={POST_B.permlink}
        linkTarget="https://peakd.com"
      />
    </div>
  </section>
</div>
