// packages/svelte/src/HiveProvider.svelte
<script lang="ts">
  import { setContext, onMount, onDestroy } from "svelte";
  import type { IHiveChainInterface } from "@hiveio/wax";
  import type { Snippet } from "svelte";
  import {
    HiveClient,
    DEFAULT_API_ENDPOINTS,
    HealthCheckerService,
    DEFAULT_HEALTHCHECKER_KEY,
    DEFAULT_HEALTHCHECKER_PROVIDERS,
    createDefaultCheckers,
    type HiveClientState,
    type ConnectionStatus,
    type EndpointStatus,
    type ApiChecker,
  } from "@kkocot/honeycomb-core";
  import { HIVE_CONTEXT_KEY, type HiveContextValue } from "./context.svelte";

  export interface HealthCheckerServiceConfig {
    key: string;
    createCheckers: (chain: IHiveChainInterface) => ApiChecker[];
    defaultProviders: string[];
    nodeAddress: string | null;
    onNodeChange: (node: string | null, chain: IHiveChainInterface) => void;
    enableLogs?: boolean;
  }

  interface Props {
    apiEndpoints?: string[];
    timeout?: number;
    healthCheckInterval?: number;
    onEndpointChange?: (endpoint: string) => void;
    healthCheckerServices?: HealthCheckerServiceConfig[];
    children: Snippet;
  }

  let {
    apiEndpoints = DEFAULT_API_ENDPOINTS,
    timeout = 5000,
    healthCheckInterval = 30000,
    onEndpointChange,
    healthCheckerServices: hc_service_configs,
    children,
  }: Props = $props();

  let chain: IHiveChainInterface | null = $state(null);
  const initial_status: ConnectionStatus = "disconnected";
  let status: ConnectionStatus = $state(initial_status);
  let current_endpoint: string | null = $state(null);
  let error: string | null = $state(null);
  let endpoints: EndpointStatus[] = $state([]);
  let is_client: boolean = $state(false);
  let is_loading: boolean = $state(false);

  let client: HiveClient | null = null;
  let unsubscribe_fn: (() => void) | null = null;
  let hc_services = new Map<string, HealthCheckerService>();

  const refresh_endpoints = async () => {
    if (client) {
      await client.refreshEndpoints();
    }
  };

  const get_health_checker_service = (
    key: string
  ): HealthCheckerService | null => {
    return hc_services.get(key) ?? null;
  };

  setContext<HiveContextValue>(HIVE_CONTEXT_KEY, {
    get chain() {
      return chain;
    },
    get status() {
      return status;
    },
    get api_endpoint() {
      return current_endpoint;
    },
    get error() {
      return error;
    },
    get is_loading() {
      return is_loading;
    },
    get endpoints() {
      return endpoints;
    },
    get is_client() {
      return is_client;
    },
    refresh_endpoints,
    get_health_checker_service,
  });

  function setup_health_checker_services(
    chain_instance: IHiveChainInterface
  ): void {
    cleanup_health_checker_services();

    const configs: HealthCheckerServiceConfig[] = hc_service_configs?.length
      ? hc_service_configs
      : [
          {
            key: DEFAULT_HEALTHCHECKER_KEY,
            createCheckers: createDefaultCheckers,
            defaultProviders: DEFAULT_HEALTHCHECKER_PROVIDERS,
            nodeAddress: null,
            onNodeChange: (node, c) => {
              if (node) {
                c.endpointUrl = node;
              }
            },
          },
        ];

    const new_services = new Map<string, HealthCheckerService>();

    for (const config of configs) {
      const checkers = config.createCheckers(chain_instance);
      const service = new HealthCheckerService(
        config.key,
        checkers,
        config.defaultProviders,
        config.nodeAddress,
        (node) => config.onNodeChange(node, chain_instance),
        config.enableLogs
      );
      new_services.set(config.key, service);
    }

    hc_services = new_services;
  }

  function cleanup_health_checker_services(): void {
    for (const service of hc_services.values()) {
      service.stopCheckingProcess();
    }
    hc_services = new Map();
  }

  onMount(() => {
    is_client = true;

    client = new HiveClient({
      endpoints: apiEndpoints,
      timeout,
      healthCheckInterval,
      onEndpointChange: (endpoint) => {
        if (onEndpointChange) {
          onEndpointChange(endpoint);
        }
      },
    });

    unsubscribe_fn = client.subscribe((new_state: HiveClientState) => {
      status = new_state.status;
      current_endpoint = new_state.currentEndpoint;
      endpoints = new_state.endpoints;
      error = new_state.error;
      is_loading =
        new_state.status === "connecting" ||
        new_state.status === "reconnecting";
      chain = client?.chain ?? null;
    });

    client
      .connect()
      .then(() => {
        chain = client?.chain ?? null;
        if (chain) {
          setup_health_checker_services(chain);
        }
      })
      .catch(() => {
        // Errors handled via state subscription
      });
  });

  onDestroy(() => {
    cleanup_health_checker_services();
    unsubscribe_fn?.();
    client?.disconnect();
    client = null;
    chain = null;
  });
</script>

{@render children()}

// packages/solid/src/hive-provider.tsx
import {
  createContext,
  useContext,
  createSignal,
  createEffect,
  onCleanup,
  createMemo,
  type ParentComponent,
  type JSX,
} from "solid-js";
import type { IHiveChainInterface } from "@hiveio/wax";
import {
  HiveClient,
  DEFAULT_API_ENDPOINTS,
  HealthCheckerService,
  DEFAULT_HEALTHCHECKER_KEY,
  DEFAULT_HEALTHCHECKER_PROVIDERS,
  createDefaultCheckers,
  type HiveClientState,
  type ConnectionStatus,
  type EndpointStatus,
  type ApiChecker,
} from "@kkocot/honeycomb-core";

// Re-export for convenience
export { DEFAULT_API_ENDPOINTS, DEFAULT_HEALTHCHECKER_KEY };

// ============== Types ==============

/**
 * Hive context value - all values are signal getters
 */
export interface HealthCheckerServiceConfig {
  /** Unique key to identify this service instance */
  key: string;
  /** Factory that receives chain and returns checkers array */
  createCheckers: (chain: IHiveChainInterface) => ApiChecker[];
  /** Default API endpoint URLs to check */
  defaultProviders: string[];
  /** Currently active node address for this service */
  nodeAddress: string | null;
  /** Callback fired when the healthchecker switches to a different node. Receives chain for convenience. */
  onNodeChange: (node: string | null, chain: IHiveChainInterface) => void;
  /** Enable console logs for debugging */
  enableLogs?: boolean;
}

export interface HiveContextValue {
  /** Hive chain instance getter - returns null during SSR and initial load */
  chain: () => IHiveChainInterface | null;
  /** Loading state getter - true while chain is initializing */
  is_loading: () => boolean;
  /** Error getter - error message if chain initialization failed */
  error: () => string | null;
  /** Client-side detection getter - check if running on client */
  is_client: () => boolean;
  /** API endpoint getter - currently connected API endpoint */
  api_endpoint: () => string | null;
  /** Connection status getter */
  status: () => ConnectionStatus;
  /** Endpoints status getter - status of all endpoints */
  endpoints: () => EndpointStatus[];
  /** Refresh all endpoints health status */
  refresh_endpoints: () => Promise<void>;
  /** Get a HealthCheckerService instance by key, null if not ready */
  getHealthCheckerService: (key: string) => HealthCheckerService | null;
}

/**
 * HiveProvider component props
 */
export interface HiveProviderProps {
  /**
   * List of API endpoints to try in priority order.
   * @default DEFAULT_API_ENDPOINTS
   */
  apiEndpoints?: string[];
  /**
   * Timeout for single request in milliseconds
   * @default 5000
   */
  timeout?: number;
  /**
   * Health check interval in milliseconds (0 = disabled)
   * @default 30000
   */
  healthCheckInterval?: number;
  /**
   * Callback fired when endpoint changes
   */
  onEndpointChange?: (endpoint: string) => void;
  /**
   * HealthChecker service configurations. Each entry creates a separate
   * HealthCheckerService instance, accessible by key via getHealthCheckerService().
   */
  healthCheckerServices?: HealthCheckerServiceConfig[];
}

// ============== Context ==============

const HiveContext = createContext<HiveContextValue | null>(null);

// ============== Provider ==============

/**
 * HiveProvider Component
 *
 * Provides Hive blockchain connectivity using @kkocot/honeycomb-core.
 * Automatically manages endpoint fallback and health monitoring.
 * SSR-compatible - safely handles server-side rendering.
 *
 * @example
 * ```tsx
 * <HiveProvider>
 *   <App />
 * </HiveProvider>
 * ```
 */
export const HiveProvider: ParentComponent<HiveProviderProps> = (props) => {
  // Client-side detection
  const [is_client, set_is_client] = createSignal(false);

  // Client state from HiveClient
  const [client_state, set_client_state] = createSignal<HiveClientState>({
    status: "disconnected",
    currentEndpoint: null,
    endpoints: [],
    error: null,
  });

  // Reactive chain reference
  const [chain_ref, set_chain_ref] = createSignal<IHiveChainInterface | null>(
    null
  );

  // Store HiveClient instance reference
  let client_instance: HiveClient | null = null;

  // HealthChecker services
  const [hc_services, set_hc_services] = createSignal<Map<string, HealthCheckerService>>(new Map());

  // Detect client-side
  createEffect(() => {
    set_is_client(true);
  });

  // Function to refresh endpoints
  const refresh_endpoints = async () => {
    if (client_instance) {
      await client_instance.refreshEndpoints();
    }
  };

  // Initialize HiveClient when on client-side
  createEffect(() => {
    if (!is_client()) return;

    // Create HiveClient instance
    client_instance = new HiveClient({
      endpoints: props.apiEndpoints || DEFAULT_API_ENDPOINTS,
      timeout: props.timeout,
      healthCheckInterval: props.healthCheckInterval,
      onEndpointChange: props.onEndpointChange,
    });

    // Subscribe to state changes
    const unsubscribe = client_instance.subscribe((state) => {
      set_client_state(state);
      set_chain_ref(client_instance?.chain ?? null);
    });

    // Connect to Hive blockchain
    client_instance
      .connect()
      .then(() => {
        set_chain_ref(client_instance?.chain ?? null);
      })
      .catch(() => {
        // Errors are handled via state subscription
      });

    // Cleanup on unmount
    onCleanup(() => {
      unsubscribe();
      client_instance?.disconnect();
      client_instance = null;
      set_chain_ref(null);
    });
  });

  // Initialize HealthCheckerService instances when chain becomes available.
  // When no healthCheckerServices are configured, create a default service
  // so that <HealthCheckerComponent healthcheckerKey="default" /> works out of the box.
  createEffect(() => {
    const chain = chain_ref();
    if (!chain) return;

    const configs: HealthCheckerServiceConfig[] =
      props.healthCheckerServices?.length
        ? props.healthCheckerServices
        : [
            {
              key: DEFAULT_HEALTHCHECKER_KEY,
              createCheckers: createDefaultCheckers,
              defaultProviders: DEFAULT_HEALTHCHECKER_PROVIDERS,
              nodeAddress: null,
              onNodeChange: (node, c) => {
                if (node) {
                  c.endpointUrl = node;
                }
              },
            },
          ];

    const new_services = new Map<string, HealthCheckerService>();

    for (const config of configs) {
      const checkers = config.createCheckers(chain);
      const service = new HealthCheckerService(
        config.key,
        checkers,
        config.defaultProviders,
        config.nodeAddress,
        (node) => config.onNodeChange(node, chain),
        config.enableLogs,
      );
      new_services.set(config.key, service);
    }

    set_hc_services(new_services);

    onCleanup(() => {
      for (const service of new_services.values()) {
        service.stopCheckingProcess();
      }
      set_hc_services(new Map());
    });
  });

  const getHealthCheckerService = (key: string): HealthCheckerService | null => {
    return hc_services().get(key) ?? null;
  };

  // Memoize context value with signal getters
  const value = createMemo<HiveContextValue>(() => ({
    chain: () => chain_ref(),
    is_loading: () => {
      const state = client_state();
      return state.status === "connecting" || state.status === "reconnecting";
    },
    error: () => client_state().error,
    is_client: () => is_client(),
    api_endpoint: () => client_state().currentEndpoint,
    status: () => client_state().status,
    endpoints: () => client_state().endpoints,
    refresh_endpoints: refresh_endpoints,
    getHealthCheckerService,
  }));

  return <HiveContext.Provider value={value()}>{props.children}</HiveContext.Provider>;
};

// ============== Hooks ==============

/**
 * Hook to access full Hive context
 * @throws Error if used outside of HiveProvider
 * @returns HiveContextValue with signal getters
 */
export function useHive(): HiveContextValue {
  const context = useContext(HiveContext);
  if (!context) {
    throw new Error("useHive must be used within a HiveProvider");
  }
  return context;
}

/**
 * Hook to access Hive chain instance
 * Returns signal getter that returns null during SSR and when not connected
 * @returns Signal getter for IHiveChainInterface | null
 */
export function useHiveChain(): () => IHiveChainInterface | null {
  const { chain } = useHive();
  return chain;
}

/**
 * Hook to get current API endpoint
 * @returns Signal getter for current endpoint URL or null
 */
export function useApiEndpoint(): () => string | null {
  const { api_endpoint } = useHive();
  return api_endpoint;
}

/**
 * Hook to get Hive connection status with endpoints info
 * @returns Signal getter for status object
 */
export function useHiveStatus(): () => {
  status: ConnectionStatus;
  endpoints: EndpointStatus[];
} {
  const { status, endpoints } = useHive();
  return createMemo(() => ({
    status: status(),
    endpoints: endpoints(),
  }));
}
