// apps/demo/components/hive/passive/manabar.tsx
"use client";

import { useState, useEffect } from "react";
import { cn } from "@/lib/utils";
import { useHive } from "@/contexts/hive-context";
import { Loader2 } from "lucide-react";

// ===========================================
// Types
// ===========================================

interface ManabarData {
  current: string;
  max: string;
  percentageValue: number;
  cooldown: number; // seconds until full
}

interface ManabarsData {
  upvote: ManabarData;
  downvote: ManabarData;
  rc: ManabarData;
}

type ManabarVariant = "full" | "compact" | "ring";

export interface HiveManabarProps {
  username: string;
  variant?: ManabarVariant;
  showLabels?: boolean;
  showValues?: boolean;
  showCooldown?: boolean;
  className?: string;
}

// ===========================================
// Utilities
// ===========================================

function formatNumber(num: string): string {
  const n = BigInt(num);
  if (n >= BigInt(1e12)) return (Number(n / BigInt(1e9)) / 1000).toFixed(1) + "T";
  if (n >= BigInt(1e9)) return (Number(n / BigInt(1e6)) / 1000).toFixed(1) + "B";
  if (n >= BigInt(1e6)) return (Number(n / BigInt(1e3)) / 1000).toFixed(1) + "M";
  if (n >= BigInt(1e3)) return (Number(n) / 1000).toFixed(1) + "K";
  return num;
}

function formatCooldown(seconds: number): string {
  if (seconds <= 0) return "Full";
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  if (hours > 24) {
    const days = Math.floor(hours / 24);
    return `${days}d ${hours % 24}h`;
  }
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m`;
}

// Calculate manabar from raw blockchain data
const MANA_REGENERATION_SECONDS = 432000; // 5 days in seconds

function calculateManabar(
  currentMana: string,
  maxMana: string,
  lastUpdateTime: number
): { current: string; max: string; percent: number; cooldown: number } {
  const now = Math.floor(Date.now() / 1000);
  const elapsed = now - lastUpdateTime;

  const maxManaNum = BigInt(maxMana);
  let currentManaNum = BigInt(currentMana);

  // Regenerate mana based on time elapsed
  const regenerated = (maxManaNum * BigInt(elapsed)) / BigInt(MANA_REGENERATION_SECONDS);
  currentManaNum = currentManaNum + regenerated;

  // Cap at max
  if (currentManaNum > maxManaNum) {
    currentManaNum = maxManaNum;
  }

  const percent = maxManaNum > BigInt(0)
    ? Number((currentManaNum * BigInt(10000)) / maxManaNum) / 100
    : 0;

  // Calculate cooldown (seconds until full)
  const remaining = maxManaNum - currentManaNum;
  const cooldown = remaining > BigInt(0)
    ? Number((remaining * BigInt(MANA_REGENERATION_SECONDS)) / maxManaNum)
    : 0;

  return {
    current: currentManaNum.toString(),
    max: maxManaNum.toString(),
    percent: Math.min(100, Math.max(0, percent)),
    cooldown,
  };
}

// ===========================================
// Ring Component (SVG circular progress)
// ===========================================

function ManaRing({
  percentage,
  color,
  size = 60,
  strokeWidth = 6,
  children,
}: {
  percentage: number;
  color: string;
  size?: number;
  strokeWidth?: number;
  children?: React.ReactNode;
}) {
  const radius = (size - strokeWidth) / 2;
  const circumference = radius * 2 * Math.PI;
  const offset = circumference - (percentage / 100) * circumference;

  return (
    <div className="relative" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        {/* Background circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="currentColor"
          strokeWidth={strokeWidth}
          className="text-muted/30"
        />
        {/* Progress circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
          className="transition-all duration-500"
        />
      </svg>
      {children && (
        <div className="absolute inset-0 flex items-center justify-center">
          {children}
        </div>
      )}
    </div>
  );
}

// ===========================================
// Single Manabar Display
// ===========================================

function SingleManabar({
  title,
  data,
  color,
  showValues,
  showCooldown,
}: {
  title: string;
  data: ManabarData;
  color: string;
  showValues?: boolean;
  showCooldown?: boolean;
}) {
  return (
    <div className="flex flex-col items-center gap-2">
      <span className="text-sm font-medium">{title}</span>
      <ManaRing percentage={data.percentageValue} color={color} size={70}>
        <span className="text-sm font-bold">{Math.round(data.percentageValue)}%</span>
      </ManaRing>
      {showValues && (
        <div className="text-xs text-muted-foreground text-center">
          <div>{formatNumber(data.current)} / {formatNumber(data.max)}</div>
        </div>
      )}
      {showCooldown && data.percentageValue < 100 && (
        <div className="text-xs text-muted-foreground">
          Full in: {formatCooldown(data.cooldown)}
        </div>
      )}
    </div>
  );
}

// ===========================================
// Main Component
// ===========================================

export function HiveManabar({
  username,
  variant = "full",
  showLabels = true,
  showValues = false,
  showCooldown = true,
  className,
}: HiveManabarProps) {
  const { chain } = useHive();
  const [isLoading, setIsLoading] = useState(true);
  const [data, setData] = useState<ManabarsData | null>(null);

  useEffect(() => {
    async function fetchManabars() {
      if (!chain || !username) return;
      setIsLoading(true);

      try {
        // Fetch account data and RC account data
        const [accountResponse, rcResponse] = await Promise.all([
          chain.api.database_api.find_accounts({ accounts: [username] }),
          chain.api.rc_api.find_rc_accounts({ accounts: [username] }),
        ]);

        if (accountResponse.accounts.length > 0 && rcResponse.rc_accounts.length > 0) {
          const acc = accountResponse.accounts[0];
          const rcAcc = rcResponse.rc_accounts[0];

          // Calculate voting mana (upvote)
          const upvoteMana = calculateManabar(
            acc.voting_manabar.current_mana.toString(),
            acc.post_voting_power.amount.toString(),
            acc.voting_manabar.last_update_time
          );

          // Calculate downvote mana (25% of voting power)
          const downvoteMax = (BigInt(acc.post_voting_power.amount) / BigInt(4)).toString();
          const downvoteMana = calculateManabar(
            acc.downvote_manabar.current_mana.toString(),
            downvoteMax,
            acc.downvote_manabar.last_update_time
          );

          // Calculate RC
          const rcMana = calculateManabar(
            rcAcc.rc_manabar.current_mana.toString(),
            rcAcc.max_rc.toString(),
            rcAcc.rc_manabar.last_update_time
          );

          setData({
            upvote: {
              current: upvoteMana.current,
              max: upvoteMana.max,
              percentageValue: upvoteMana.percent,
              cooldown: upvoteMana.cooldown,
            },
            downvote: {
              current: downvoteMana.current,
              max: downvoteMana.max,
              percentageValue: downvoteMana.percent,
              cooldown: downvoteMana.cooldown,
            },
            rc: {
              current: rcMana.current,
              max: rcMana.max,
              percentageValue: rcMana.percent,
              cooldown: rcMana.cooldown,
            },
          });
        }
      } catch (err) {
        console.error("Failed to fetch manabars:", err);
      } finally {
        setIsLoading(false);
      }
    }

    fetchManabars();
    // Refresh every minute
    const interval = setInterval(fetchManabars, 60000);
    return () => clearInterval(interval);
  }, [chain, username]);

  if (isLoading) {
    return (
      <div className={cn("flex items-center justify-center p-4", className)}>
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!data) {
    return (
      <div className={cn("text-sm text-muted-foreground p-4", className)}>
        Failed to load manabars
      </div>
    );
  }

  // Compact variant - just rings in a row
  if (variant === "compact") {
    return (
      <div className={cn("flex items-center gap-3", className)}>
        <ManaRing percentage={data.upvote.percentageValue} color="#00C040" size={40} strokeWidth={4}>
          <span className="text-[10px] font-bold text-green-500">
            {Math.round(data.upvote.percentageValue)}
          </span>
        </ManaRing>
        <ManaRing percentage={data.downvote.percentageValue} color="#C01000" size={40} strokeWidth={4}>
          <span className="text-[10px] font-bold text-red-500">
            {Math.round(data.downvote.percentageValue)}
          </span>
        </ManaRing>
        <ManaRing percentage={data.rc.percentageValue} color="#0088FE" size={40} strokeWidth={4}>
          <span className="text-[10px] font-bold text-blue-500">
            {Math.round(data.rc.percentageValue)}
          </span>
        </ManaRing>
      </div>
    );
  }

  // Ring variant - single combined ring (shows RC only)
  if (variant === "ring") {
    return (
      <div className={cn("relative", className)}>
        <ManaRing percentage={data.rc.percentageValue} color="#0088FE" size={50} strokeWidth={5}>
          <span className="text-xs font-bold">{Math.round(data.rc.percentageValue)}%</span>
        </ManaRing>
      </div>
    );
  }

  // Full variant - detailed view
  return (
    <div className={cn("flex flex-wrap justify-center gap-6", className)}>
      <SingleManabar
        title={showLabels ? "Voting Power" : ""}
        data={data.upvote}
        color="#00C040"
        showValues={showValues}
        showCooldown={showCooldown}
      />
      <SingleManabar
        title={showLabels ? "Downvote" : ""}
        data={data.downvote}
        color="#C01000"
        showValues={showValues}
        showCooldown={showCooldown}
      />
      <SingleManabar
        title={showLabels ? "Resource Credits" : ""}
        data={data.rc}
        color="#0088FE"
        showValues={showValues}
        showCooldown={showCooldown}
      />
    </div>
  );
}

// packages/solid/src/manabar.tsx
import {
  createSignal,
  createEffect,
  onCleanup,
  Show,
  Switch,
  Match,
  type Component,
  type JSX,
} from "solid-js";
import { useHive } from "./hive-provider";
import { cn } from "./utils";
import {
  calculate_manabar,
  format_mana_number,
  format_cooldown,
  type ManabarData,
} from "@kkocot/honeycomb-core";

export type ManabarVariant = "full" | "compact" | "ring";

export interface HiveManabarProps {
  username: string;
  variant?: ManabarVariant;
  showLabels?: boolean;
  showValues?: boolean;
  showCooldown?: boolean;
  class?: string;
}

interface ManabarsState {
  upvote: ManabarData;
  downvote: ManabarData;
  rc: ManabarData;
}

const MANA_COLORS = {
  upvote: "#00C040",
  downvote: "#C01000",
  rc: "#0088FE",
};

function ManaRing(props: {
  percentage: number;
  color: string;
  size?: number;
  stroke_width?: number;
  children?: JSX.Element;
}) {
  const size = () => props.size ?? 60;
  const stroke_width = () => props.stroke_width ?? 6;
  const radius = () => (size() - stroke_width()) / 2;
  const circumference = () => radius() * 2 * Math.PI;
  const offset = () =>
    circumference() - (props.percentage / 100) * circumference();

  return (
    <div class="relative" style={{ width: `${size()}px`, height: `${size()}px` }}>
      <svg width={size()} height={size()} class="-rotate-90">
        <circle
          cx={size() / 2}
          cy={size() / 2}
          r={radius()}
          fill="none"
          stroke="currentColor"
          stroke-width={stroke_width()}
          class="text-hive-muted/30"
        />
        <circle
          cx={size() / 2}
          cy={size() / 2}
          r={radius()}
          fill="none"
          stroke={props.color}
          stroke-width={stroke_width()}
          stroke-dasharray={circumference()}
          stroke-dashoffset={offset()}
          stroke-linecap="round"
          class="transition-all duration-500"
        />
      </svg>
      <Show when={props.children}>
        <div class="absolute inset-0 flex items-center justify-center">
          {props.children}
        </div>
      </Show>
    </div>
  );
}

function SingleManabar(props: {
  title: string;
  data: ManabarData;
  color: string;
  show_values?: boolean;
  show_cooldown?: boolean;
}) {
  return (
    <div class="flex flex-col items-center gap-2">
      <Show when={props.title}>
        <span class="text-sm font-medium text-hive-foreground">
          {props.title}
        </span>
      </Show>
      <ManaRing percentage={props.data.percentage} color={props.color} size={70}>
        <span class="text-sm font-bold text-hive-foreground">
          {Math.round(props.data.percentage)}%
        </span>
      </ManaRing>
      <Show when={props.show_values}>
        <div class="text-xs text-hive-muted-foreground text-center">
          {format_mana_number(props.data.current)} /{" "}
          {format_mana_number(props.data.max)}
        </div>
      </Show>
      <Show when={props.show_cooldown && props.data.percentage < 100}>
        <div class="text-xs text-hive-muted-foreground">
          Full in: {format_cooldown(props.data.cooldown)}
        </div>
      </Show>
    </div>
  );
}

export const HiveManabar: Component<HiveManabarProps> = (props) => {
  const hive = useHive();
  const [is_loading, set_is_loading] = createSignal(true);
  const [data, set_data] = createSignal<ManabarsState | null>(null);
  const [error, set_error] = createSignal<Error | null>(null);

  const variant = () => props.variant ?? "full";
  const show_labels = () => props.showLabels !== false;
  const show_values = () => props.showValues ?? false;
  const show_cooldown = () => props.showCooldown !== false;

  createEffect(() => {
    const chain = hive.chain();
    const username = props.username;

    if (!chain || !username) return;

    let cancelled = false;

    async function fetch_manabars() {
      if (!chain || !username) return;

      try {
        const [account_response, rc_response] = await Promise.all([
          chain.api.database_api.find_accounts({ accounts: [username.toLowerCase()] }),
          chain.api.rc_api.find_rc_accounts({ accounts: [username.toLowerCase()] }),
        ]);

        if (cancelled) return;

        if (
          account_response.accounts.length === 0 ||
          rc_response.rc_accounts.length === 0
        ) {
          set_error(new Error("User not found"));
          set_is_loading(false);
          return;
        }

        const acc = account_response.accounts[0];
        const rc_acc = rc_response.rc_accounts[0];

        const upvote = calculate_manabar(
          acc.voting_manabar.current_mana.toString(),
          acc.post_voting_power.amount.toString(),
          acc.voting_manabar.last_update_time,
        );

        const downvote_max = (
          BigInt(acc.post_voting_power.amount) / BigInt(4)
        ).toString();
        const downvote = calculate_manabar(
          acc.downvote_manabar.current_mana.toString(),
          downvote_max,
          acc.downvote_manabar.last_update_time,
        );

        const rc = calculate_manabar(
          rc_acc.rc_manabar.current_mana.toString(),
          rc_acc.max_rc.toString(),
          rc_acc.rc_manabar.last_update_time,
        );

        set_data({ upvote, downvote, rc });
        set_error(null);
      } catch {
        if (!cancelled) {
          set_error(new Error("Failed to load manabars"));
        }
      } finally {
        if (!cancelled) {
          set_is_loading(false);
        }
      }
    }

    set_is_loading(true);
    fetch_manabars();

    const interval = setInterval(fetch_manabars, 60000);

    onCleanup(() => {
      cancelled = true;
      clearInterval(interval);
    });
  });

  return (
    <Show
      when={!is_loading()}
      fallback={
        <div
          class={cn(
            "rounded-lg border border-hive-border bg-hive-card p-4 animate-pulse",
            props.class,
          )}
        >
          <div class="flex justify-center gap-6">
            <div class="h-[70px] w-[70px] rounded-full bg-hive-muted" />
            <div class="h-[70px] w-[70px] rounded-full bg-hive-muted" />
            <div class="h-[70px] w-[70px] rounded-full bg-hive-muted" />
          </div>
        </div>
      }
    >
      <Show
        when={!error() && data()}
        fallback={
          <div
            class={cn(
              "rounded-lg border border-hive-border bg-hive-card p-4",
              props.class,
            )}
          >
            <p class="text-sm text-hive-muted-foreground">
              {error()?.message ?? "Failed to load manabars"}
            </p>
          </div>
        }
      >
        {(safe_data) => (
          <Switch>
            <Match when={variant() === "compact"}>
              <div class={cn("flex items-center gap-3", props.class)}>
                <ManaRing
                  percentage={safe_data().upvote.percentage}
                  color={MANA_COLORS.upvote}
                  size={40}
                  stroke_width={4}
                >
                  <span
                    class="text-[10px] font-bold"
                    style={{ color: MANA_COLORS.upvote }}
                  >
                    {Math.round(safe_data().upvote.percentage)}
                  </span>
                </ManaRing>
                <ManaRing
                  percentage={safe_data().downvote.percentage}
                  color={MANA_COLORS.downvote}
                  size={40}
                  stroke_width={4}
                >
                  <span
                    class="text-[10px] font-bold"
                    style={{ color: MANA_COLORS.downvote }}
                  >
                    {Math.round(safe_data().downvote.percentage)}
                  </span>
                </ManaRing>
                <ManaRing
                  percentage={safe_data().rc.percentage}
                  color={MANA_COLORS.rc}
                  size={40}
                  stroke_width={4}
                >
                  <span
                    class="text-[10px] font-bold"
                    style={{ color: MANA_COLORS.rc }}
                  >
                    {Math.round(safe_data().rc.percentage)}
                  </span>
                </ManaRing>
              </div>
            </Match>

            <Match when={variant() === "ring"}>
              <div class={cn("relative", props.class)}>
                <ManaRing
                  percentage={safe_data().rc.percentage}
                  color={MANA_COLORS.rc}
                  size={50}
                  stroke_width={5}
                >
                  <span class="text-xs font-bold text-hive-foreground">
                    {Math.round(safe_data().rc.percentage)}%
                  </span>
                </ManaRing>
              </div>
            </Match>

            <Match when={variant() === "full"}>
              <div
                class={cn("flex flex-wrap justify-center gap-6", props.class)}
              >
                <SingleManabar
                  title={show_labels() ? "Voting Power" : ""}
                  data={safe_data().upvote}
                  color={MANA_COLORS.upvote}
                  show_values={show_values()}
                  show_cooldown={show_cooldown()}
                />
                <SingleManabar
                  title={show_labels() ? "Downvote" : ""}
                  data={safe_data().downvote}
                  color={MANA_COLORS.downvote}
                  show_values={show_values()}
                  show_cooldown={show_cooldown()}
                />
                <SingleManabar
                  title={show_labels() ? "Resource Credits" : ""}
                  data={safe_data().rc}
                  color={MANA_COLORS.rc}
                  show_values={show_values()}
                  show_cooldown={show_cooldown()}
                />
              </div>
            </Match>
          </Switch>
        )}
      </Show>
    </Show>
  );
};
