// apps/docs/app/(docs)/[framework]/post-list/page.tsx
import Link from "next/link";
import {
  ArrowLeft,
  ChevronLeft,
  ChevronRight,
  Info,
  MessageCircle,
  Pin,
  ThumbsUp,
  User,
} from "lucide-react";
import { CodeBlock } from "@/components/code-block";
import { parseFramework } from "@/lib/framework";
import { CODE } from "./post_list_data";

interface PageProps {
  params: Promise<{ framework: string }>;
}

export default async function PostListPage({ params }: PageProps) {
  const { framework: raw_framework } = await params;
  const framework = parseFramework(raw_framework);

  return (
    <article className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">HivePostList</h1>
        <p className="mt-2 text-lg text-muted-foreground">
          Ranked post feed with sorting, pagination, pinned posts, and multiple
          layout variants.
        </p>
      </div>

      {/* Info */}
      <section className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4">
        <div className="flex gap-3">
          <Info className="h-5 w-5 text-blue-500 shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-blue-500">
              Uses bridge.get_ranked_posts
            </p>
            <p className="mt-1 text-sm text-muted-foreground">
              Fetches ranked posts from the Hive blockchain via the Bridge API.
              Supports sorting by trending, hot, created, payout, and muted.
              Requires HiveProvider wrapper.
            </p>
          </div>
        </div>
      </section>

      {/* Usage */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Usage</h2>
        <CodeBlock
          code={CODE.basic[framework]}
          language={framework === "vue" ? "vue" : "tsx"}
        />
      </section>

      {/* Preview */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Preview</h2>
        <div className="rounded-lg border border-border p-6">
          <div className="space-y-4">
            {/* Sort controls */}
            <div className="flex gap-2">
              {["Trending", "Hot", "Created", "Payout"].map((label, i) => (
                <button
                  key={label}
                  className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
                    i === 0
                      ? "bg-hive-red text-white"
                      : "bg-muted text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>

            {/* Pinned post */}
            <div className="flex gap-4 rounded-lg border border-hive-red/20 bg-hive-red/5 p-4">
              <div className="w-16 h-16 rounded bg-muted shrink-0 flex items-center justify-center">
                <User className="h-6 w-6 text-muted-foreground" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <Pin className="h-3.5 w-3.5 text-hive-red" />
                  <span className="text-xs font-medium text-hive-red">
                    Pinned
                  </span>
                </div>
                <h3 className="font-semibold truncate mt-1">
                  Welcome to Hive - Getting Started Guide
                </h3>
                <p className="text-sm text-muted-foreground">
                  @hiveio
                </p>
                <div className="flex items-center gap-4 mt-2 text-sm text-muted-foreground">
                  <span className="flex items-center gap-1">
                    <ThumbsUp className="h-3.5 w-3.5" /> 312
                  </span>
                  <span className="flex items-center gap-1">
                    <MessageCircle className="h-3.5 w-3.5" /> 87
                  </span>
                  <span className="text-green-500">$124.50</span>
                </div>
              </div>
            </div>

            {/* Regular posts */}
            {[
              {
                title: "Building DApps on Hive Blockchain",
                author: "barddev",
                votes: 89,
                comments: 24,
                payout: "$15.30",
              },
              {
                title: "Weekly Development Update #42",
                author: "hivebuzz",
                votes: 156,
                comments: 45,
                payout: "$32.10",
              },
              {
                title: "Understanding Resource Credits",
                author: "peakd",
                votes: 67,
                comments: 12,
                payout: "$8.75",
              },
            ].map((post) => (
              <div
                key={post.title}
                className="flex gap-4 rounded-lg border border-border p-4"
              >
                <div className="w-16 h-16 rounded bg-muted shrink-0 flex items-center justify-center">
                  <User className="h-6 w-6 text-muted-foreground" />
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="font-semibold truncate">{post.title}</h3>
                  <p className="text-sm text-muted-foreground">
                    @{post.author}
                  </p>
                  <div className="flex items-center gap-4 mt-2 text-sm text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <ThumbsUp className="h-3.5 w-3.5" /> {post.votes}
                    </span>
                    <span className="flex items-center gap-1">
                      <MessageCircle className="h-3.5 w-3.5" /> {post.comments}
                    </span>
                    <span className="text-green-500">{post.payout}</span>
                  </div>
                </div>
              </div>
            ))}

            {/* Pagination */}
            <div className="flex items-center justify-between pt-2">
              <button className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground opacity-50 cursor-not-allowed">
                <ChevronLeft className="h-4 w-4" />
                Previous
              </button>
              <span className="text-sm text-muted-foreground">Page 1</span>
              <button className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-1.5 text-sm hover:bg-accent transition-colors">
                Next
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Props */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Props</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="py-3 px-4 text-left font-semibold">Prop</th>
                <th className="py-3 px-4 text-left font-semibold">Type</th>
                <th className="py-3 px-4 text-left font-semibold">Default</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              <tr>
                <td className="py-3 px-4">
                  <code>sort</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>{`"trending" | "hot" | "created" | "payout" | "muted"`}</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>"trending"</code>
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>tag</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>string</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">-</td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>limit</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>number</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>20</code>
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>pinned_posts</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>{`Array<{ author: string; permlink: string }>`}</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>[]</code>
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>show_sort_controls</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>boolean</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>false</code>
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>variant</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>{`"card" | "compact" | "grid"`}</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>"compact"</code>
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>hide</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>{`("author" | "thumbnail" | "payout" | "votes" | "comments" | "time")[]`}</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>[]</code>
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>linkTarget</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>string</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>{`"https://blog.openhive.network"`}</code>
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>
                    {framework === "react" ? "className" : "class"}
                  </code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>string</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">-</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* Hook */}
      <section>
        <h2 className="text-xl font-semibold mb-4">useHivePostList Hook</h2>
        <p className="text-muted-foreground mb-4">
          For full control over the post feed, use the{" "}
          <code className="rounded bg-muted px-1.5 py-0.5 text-sm">
            useHivePostList
          </code>{" "}
          hook directly. It returns posts, loading state, pagination controls,
          and sort management.
        </p>

        <h3 className="text-sm font-medium mb-2">Return values</h3>
        <div className="overflow-x-auto mb-4">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="py-3 px-4 text-left font-semibold">Property</th>
                <th className="py-3 px-4 text-left font-semibold">Type</th>
                <th className="py-3 px-4 text-left font-semibold">
                  Description
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              <tr>
                <td className="py-3 px-4">
                  <code>posts</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>RankedPost[]</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Current page of ranked posts
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>is_loading</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>boolean</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Whether data is being fetched
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>error</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>Error | null</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Fetch error, if any
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>sort</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>SortType</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Current sort method
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>set_sort</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>(sort: SortType) =&gt; void</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Change sort method (resets to page 1)
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>page</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>number</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Current page number
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>has_prev</code> / <code>has_next</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>boolean</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Whether previous/next page exists
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>prev_page</code> / <code>next_page</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>() =&gt; void</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Navigate to previous/next page
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <h3 className="text-sm font-medium mb-2">Example</h3>
        <CodeBlock
          code={CODE.hookUsage[framework]}
          language={framework === "vue" ? "vue" : "tsx"}
        />
      </section>

      {/* Examples */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Examples</h2>
        <div className="space-y-6">
          <div>
            <h3 className="text-sm font-medium mb-2">Sort controls</h3>
            <CodeBlock
              code={CODE.sortControls[framework]}
              language={framework === "vue" ? "vue" : "tsx"}
            />
          </div>
          <div>
            <h3 className="text-sm font-medium mb-2">Pinned posts</h3>
            <CodeBlock
              code={CODE.pinnedPosts[framework]}
              language={framework === "vue" ? "vue" : "tsx"}
            />
          </div>
          <div>
            <h3 className="text-sm font-medium mb-2">Variants</h3>
            <CodeBlock
              code={CODE.variants[framework]}
              language={framework === "vue" ? "vue" : "tsx"}
            />
          </div>
          <div>
            <h3 className="text-sm font-medium mb-2">Hide elements</h3>
            <CodeBlock
              code={CODE.hideElements[framework]}
              language={framework === "vue" ? "vue" : "tsx"}
            />
          </div>
        </div>
      </section>

      {/* Navigation */}
      <section className="flex items-center justify-between">
        <Link
          href={`/${framework}/post-card`}
          className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-medium transition-colors hover:bg-accent"
        >
          <ArrowLeft className="h-4 w-4" />
          Post Card
        </Link>
        <div />
      </section>
    </article>
  );
}

// packages/solid/src/post-list.tsx
import { Show, For, Switch, Match, type Component } from "solid-js";
import {
  useHivePostList,
  type UseHivePostListOptions,
} from "./use-hive-post-list";
import { useHivePost } from "./use-hive-post";
import { HiveAvatar } from "./avatar";
import { cn } from "./utils";
import type { PostVariant, PostHideOption } from "./post-card";
import {
  type SortType,
  type RankedPost,
  format_payout,
  format_time_ago,
  extract_thumbnail,
} from "@kkocot/honeycomb-core";

const SORT_LABELS: Record<SortType, string> = {
  trending: "Trending",
  hot: "Hot",
  created: "New",
  payout: "Payout",
  muted: "Muted",
};

const SORT_OPTIONS: SortType[] = [
  "trending",
  "hot",
  "created",
  "payout",
  "muted",
];

export interface HivePostListProps {
  sort?: SortType;
  tag?: string;
  limit?: number;
  pinned_posts?: Array<{ author: string; permlink: string }>;
  show_sort_controls?: boolean;
  variant?: PostVariant;
  hide?: PostHideOption[];
  linkTarget?: string;
  class?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function should_hide(hide: PostHideOption[], option: PostHideOption): boolean {
  return hide.includes(option);
}

function strip_markdown(text: string): string {
  return text.replace(/[#*`>\[\]!]/g, "").substring(0, 150);
}

function get_thumbnail(post: RankedPost): string | null {
  return extract_thumbnail(post.json_metadata, post.body) ?? null;
}

function get_post_url(
  author: string,
  permlink: string,
  category: string,
  link_target: string,
): string {
  return category
    ? `${link_target}/${category}/@${author}/${permlink}`
    : `${link_target}/@${author}/${permlink}`;
}

// ---------------------------------------------------------------------------
// Sort Controls
// ---------------------------------------------------------------------------

const SortControls: Component<{
  sort: SortType;
  on_change: (s: SortType) => void;
}> = (props) => {
  return (
    <div class="flex flex-wrap gap-2 mb-4">
      <For each={SORT_OPTIONS}>
        {(option) => (
          <button
            type="button"
            onClick={() => props.on_change(option)}
            class={cn(
              "rounded-lg px-3 py-1.5 text-sm font-medium transition-colors",
              option === props.sort
                ? "bg-foreground text-background"
                : "bg-hive-muted text-hive-muted-foreground hover:text-hive-foreground",
            )}
          >
            {SORT_LABELS[option]}
          </button>
        )}
      </For>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Inline Post Renderers
// ---------------------------------------------------------------------------

interface InlinePostProps {
  post: RankedPost;
  hide: PostHideOption[];
  link_target: string;
  is_pinned?: boolean;
}

const CompactPost: Component<InlinePostProps> = (props) => {
  const thumbnail = () => get_thumbnail(props.post);
  const post_url = () =>
    get_post_url(
      props.post.author,
      props.post.permlink,
      props.post.category,
      props.link_target,
    );

  return (
    <div class="flex gap-4 p-4 rounded-lg border border-hive-border bg-hive-card hover:border-hive-red/50 transition-colors">
      <Show when={!should_hide(props.hide, "thumbnail")}>
        <a
          href={post_url()}
          target="_blank"
          rel="noopener noreferrer"
          class="w-20 h-20 rounded overflow-hidden shrink-0"
        >
          <Show
            when={thumbnail()}
            fallback={
              <div class="w-full h-full bg-hive-muted flex items-center justify-center text-hive-muted-foreground text-xs">
                No img
              </div>
            }
          >
            <img
              src={thumbnail() ?? ""}
              alt={props.post.title}
              class="w-full h-full object-cover"
            />
          </Show>
        </a>
      </Show>
      <div class="flex-1 min-w-0">
        <div class="flex items-center gap-2">
          <a
            href={post_url()}
            target="_blank"
            rel="noopener noreferrer"
            class="hover:text-hive-red transition-colors min-w-0"
          >
            <h3 class="font-semibold truncate">{props.post.title}</h3>
          </a>
          <Show when={props.is_pinned}>
            <span class="shrink-0 rounded bg-hive-red px-2 py-0.5 text-xs text-white">
              Pinned
            </span>
          </Show>
        </div>
        <Show when={!should_hide(props.hide, "author")}>
          <p class="text-sm text-hive-muted-foreground">
            @{props.post.author}
            <Show when={!should_hide(props.hide, "time")}>
              {` \u00B7 ${format_time_ago(props.post.created)}`}
            </Show>
          </p>
        </Show>
        <div class="flex items-center gap-4 mt-2 text-sm text-hive-muted-foreground">
          <Show when={!should_hide(props.hide, "votes")}>
            <span class="flex items-center gap-1">
              <span aria-hidden="true">^</span> {props.post.net_votes}
            </span>
          </Show>
          <Show when={!should_hide(props.hide, "comments")}>
            <span class="flex items-center gap-1">
              <span aria-hidden="true">#</span> {props.post.children}
            </span>
          </Show>
          <Show when={!should_hide(props.hide, "payout")}>
            <span class="text-hive-success">
              {format_payout(props.post.pending_payout_value)}
            </span>
          </Show>
        </div>
      </div>
    </div>
  );
};

const CardPost: Component<InlinePostProps> = (props) => {
  const thumbnail = () => get_thumbnail(props.post);
  const post_url = () =>
    get_post_url(
      props.post.author,
      props.post.permlink,
      props.post.category,
      props.link_target,
    );

  return (
    <div class="rounded-lg border border-hive-border bg-hive-card overflow-hidden hover:border-hive-red/50 transition-colors">
      <Show when={!should_hide(props.hide, "thumbnail") && thumbnail()}>
        <a
          href={post_url()}
          target="_blank"
          rel="noopener noreferrer"
          class="block aspect-video overflow-hidden"
        >
          <img
            src={thumbnail() ?? ""}
            alt={props.post.title}
            class="w-full h-full object-cover hover:scale-105 transition-transform"
          />
        </a>
      </Show>
      <div class="p-4">
        <Show when={!should_hide(props.hide, "author")}>
          <div class="flex items-center gap-3 mb-3">
            <HiveAvatar username={props.post.author} size="sm" />
            <div>
              <p class="font-medium">@{props.post.author}</p>
              <Show when={!should_hide(props.hide, "time")}>
                <p class="text-sm text-hive-muted-foreground">
                  {format_time_ago(props.post.created)}
                </p>
              </Show>
            </div>
            <Show when={props.is_pinned}>
              <span class="ml-auto shrink-0 rounded bg-hive-red px-2 py-0.5 text-xs text-white">
                Pinned
              </span>
            </Show>
          </div>
        </Show>
        <a
          href={post_url()}
          target="_blank"
          rel="noopener noreferrer"
          class="hover:text-hive-red transition-colors"
        >
          <h2 class="text-lg font-bold">{props.post.title}</h2>
        </a>
        <p class="mt-2 text-hive-muted-foreground text-sm line-clamp-2">
          {strip_markdown(props.post.body)}...
        </p>
        <div class="flex items-center justify-between mt-4 pt-3 border-t border-hive-border">
          <div class="flex items-center gap-4 text-hive-muted-foreground">
            <Show when={!should_hide(props.hide, "votes")}>
              <span class="flex items-center gap-1.5">
                <span aria-hidden="true">^</span> {props.post.net_votes}
              </span>
            </Show>
            <Show when={!should_hide(props.hide, "comments")}>
              <span class="flex items-center gap-1.5">
                <span aria-hidden="true">#</span> {props.post.children}
              </span>
            </Show>
          </div>
          <Show when={!should_hide(props.hide, "payout")}>
            <span class="text-sm font-medium text-hive-success">
              {format_payout(props.post.pending_payout_value)}
            </span>
          </Show>
        </div>
      </div>
    </div>
  );
};

const GridPost: Component<InlinePostProps> = (props) => {
  const thumbnail = () => get_thumbnail(props.post);
  const post_url = () =>
    get_post_url(
      props.post.author,
      props.post.permlink,
      props.post.category,
      props.link_target,
    );

  return (
    <div class="rounded-lg border border-hive-border bg-hive-card overflow-hidden hover:border-hive-red/50 transition-colors">
      <Show when={!should_hide(props.hide, "thumbnail")}>
        <a
          href={post_url()}
          target="_blank"
          rel="noopener noreferrer"
          class="block aspect-video overflow-hidden"
        >
          <Show
            when={thumbnail()}
            fallback={
              <div class="w-full h-full bg-hive-muted flex items-center justify-center text-hive-muted-foreground text-sm">
                No image
              </div>
            }
          >
            <img
              src={thumbnail() ?? ""}
              alt={props.post.title}
              class="w-full h-full object-cover hover:scale-105 transition-transform"
            />
          </Show>
        </a>
      </Show>
      <div class="p-4">
        <div class="flex items-center gap-2">
          <a
            href={post_url()}
            target="_blank"
            rel="noopener noreferrer"
            class="hover:text-hive-red transition-colors min-w-0"
          >
            <h3 class="font-semibold line-clamp-2">{props.post.title}</h3>
          </a>
          <Show when={props.is_pinned}>
            <span class="shrink-0 rounded bg-hive-red px-2 py-0.5 text-xs text-white">
              Pinned
            </span>
          </Show>
        </div>
        <Show when={!should_hide(props.hide, "author")}>
          <p class="mt-1 text-sm text-hive-muted-foreground">
            @{props.post.author}
            <Show when={!should_hide(props.hide, "time")}>
              {` \u00B7 ${format_time_ago(props.post.created)}`}
            </Show>
          </p>
        </Show>
        <div class="flex items-center justify-between mt-3 pt-3 border-t border-hive-border text-sm">
          <div class="flex items-center gap-3 text-hive-muted-foreground">
            <Show when={!should_hide(props.hide, "votes")}>
              <span class="flex items-center gap-1">
                <span aria-hidden="true">^</span> {props.post.net_votes}
              </span>
            </Show>
            <Show when={!should_hide(props.hide, "comments")}>
              <span class="flex items-center gap-1">
                <span aria-hidden="true">#</span> {props.post.children}
              </span>
            </Show>
          </div>
          <Show when={!should_hide(props.hide, "payout")}>
            <span class="font-medium text-hive-success">
              {format_payout(props.post.pending_payout_value)}
            </span>
          </Show>
        </div>
      </div>
    </div>
  );
};

function PostItem(props: InlinePostProps & { variant: PostVariant }) {
  return (
    <Switch>
      <Match when={props.variant === "compact"}>
        <CompactPost
          post={props.post}
          hide={props.hide}
          link_target={props.link_target}
          is_pinned={props.is_pinned}
        />
      </Match>
      <Match when={props.variant === "grid"}>
        <GridPost
          post={props.post}
          hide={props.hide}
          link_target={props.link_target}
          is_pinned={props.is_pinned}
        />
      </Match>
      <Match when={props.variant === "card"}>
        <CardPost
          post={props.post}
          hide={props.hide}
          link_target={props.link_target}
          is_pinned={props.is_pinned}
        />
      </Match>
    </Switch>
  );
}

// ---------------------------------------------------------------------------
// Skeletons
// ---------------------------------------------------------------------------

function CompactSkeleton() {
  return (
    <div class="flex gap-4 p-4 rounded-lg border border-hive-border bg-hive-card animate-pulse">
      <div class="w-20 h-20 rounded bg-hive-muted shrink-0" />
      <div class="flex-1 space-y-2">
        <div class="h-5 w-3/4 bg-hive-muted rounded" />
        <div class="h-3 w-1/3 bg-hive-muted rounded" />
        <div class="h-3 w-1/2 bg-hive-muted rounded" />
      </div>
    </div>
  );
}

function CardSkeleton() {
  return (
    <div class="rounded-lg border border-hive-border bg-hive-card p-4 animate-pulse">
      <div class="flex items-center gap-3 mb-3">
        <div class="h-10 w-10 rounded-full bg-hive-muted" />
        <div class="space-y-2">
          <div class="h-4 w-24 bg-hive-muted rounded" />
          <div class="h-3 w-16 bg-hive-muted rounded" />
        </div>
      </div>
      <div class="h-5 w-3/4 bg-hive-muted rounded mb-2" />
      <div class="h-3 w-full bg-hive-muted rounded mb-1" />
      <div class="h-3 w-2/3 bg-hive-muted rounded" />
    </div>
  );
}

function GridSkeleton() {
  return (
    <div class="rounded-lg border border-hive-border bg-hive-card overflow-hidden animate-pulse">
      <div class="aspect-video bg-hive-muted" />
      <div class="p-4 space-y-2">
        <div class="h-5 w-3/4 bg-hive-muted rounded" />
        <div class="h-3 w-1/3 bg-hive-muted rounded" />
      </div>
    </div>
  );
}

function LoadingSkeleton(props: { variant: PostVariant; count: number }) {
  const items = () =>
    Array.from({ length: props.count }, (_, i) => i);

  return (
    <Switch>
      <Match when={props.variant === "grid"}>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <For each={items()}>{() => <GridSkeleton />}</For>
        </div>
      </Match>
      <Match when={props.variant === "compact"}>
        <div class="flex flex-col gap-2">
          <For each={items()}>{() => <CompactSkeleton />}</For>
        </div>
      </Match>
      <Match when={props.variant === "card"}>
        <div class="flex flex-col gap-4">
          <For each={items()}>{() => <CardSkeleton />}</For>
        </div>
      </Match>
    </Switch>
  );
}

// ---------------------------------------------------------------------------
// Pinned Posts
// ---------------------------------------------------------------------------

const PinnedPostItem: Component<{
  author: string;
  permlink: string;
  hide: PostHideOption[];
  link_target: string;
}> = (props) => {
  const { post, is_loading, error } = useHivePost(props.author, props.permlink);

  const post_url = () => {
    const p = post();
    if (!p) return "#";
    return get_post_url(props.author, props.permlink, p.category, props.link_target);
  };

  return (
    <Show when={!is_loading()} fallback={<CompactSkeleton />}>
      <Show
        when={!error() && post()}
        fallback={
          <div class="rounded-lg border border-hive-border bg-hive-card p-4">
            <p class="text-sm text-hive-muted-foreground">
              {error()?.message ?? `Could not load @${props.author}/${props.permlink}`}
            </p>
          </div>
        }
      >
        <div class="flex gap-4 p-4 rounded-lg border border-hive-border bg-hive-card hover:border-hive-red/50 transition-colors">
          <Show when={!should_hide(props.hide, "thumbnail")}>
            <a
              href={post_url()}
              target="_blank"
              rel="noopener noreferrer"
              class="w-20 h-20 rounded overflow-hidden shrink-0"
            >
              <Show
                when={post()?.thumbnail}
                fallback={
                  <div class="w-full h-full bg-hive-muted flex items-center justify-center text-hive-muted-foreground text-xs">
                    No img
                  </div>
                }
              >
                <img
                  src={post()?.thumbnail ?? ""}
                  alt={post()?.title ?? ""}
                  class="w-full h-full object-cover"
                />
              </Show>
            </a>
          </Show>
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2">
              <a
                href={post_url()}
                target="_blank"
                rel="noopener noreferrer"
                class="hover:text-hive-red transition-colors min-w-0"
              >
                <h3 class="font-semibold truncate">{post()?.title}</h3>
              </a>
              <span class="shrink-0 rounded bg-hive-red px-2 py-0.5 text-xs text-white">
                Pinned
              </span>
            </div>
            <Show when={!should_hide(props.hide, "author")}>
              <p class="text-sm text-hive-muted-foreground">
                @{props.author}
                <Show when={!should_hide(props.hide, "time")}>
                  {` \u00B7 ${post()?.created}`}
                </Show>
              </p>
            </Show>
            <div class="flex items-center gap-4 mt-2 text-sm text-hive-muted-foreground">
              <Show when={!should_hide(props.hide, "votes")}>
                <span class="flex items-center gap-1">
                  <span aria-hidden="true">^</span> {post()?.votes}
                </span>
              </Show>
              <Show when={!should_hide(props.hide, "comments")}>
                <span class="flex items-center gap-1">
                  <span aria-hidden="true">#</span> {post()?.comments}
                </span>
              </Show>
              <Show when={!should_hide(props.hide, "payout")}>
                <span class="text-hive-success">{post()?.payout}</span>
              </Show>
            </div>
          </div>
        </div>
      </Show>
    </Show>
  );
};

// ---------------------------------------------------------------------------
// Pagination Controls
// ---------------------------------------------------------------------------

const PaginationControls: Component<{
  page: number;
  has_prev: boolean;
  has_next: boolean;
  on_prev: () => void;
  on_next: () => void;
}> = (props) => {
  return (
    <div class="flex items-center justify-between mt-6">
      <button
        type="button"
        onClick={props.on_prev}
        disabled={!props.has_prev}
        class={cn(
          "rounded-lg border border-hive-border px-4 py-2 text-sm font-medium hover:bg-hive-muted transition-colors",
          !props.has_prev &&
            "opacity-50 cursor-not-allowed hover:bg-transparent",
        )}
      >
        Prev Page
      </button>
      <span class="text-sm text-hive-muted-foreground">
        Page {props.page}
      </span>
      <button
        type="button"
        onClick={props.on_next}
        disabled={!props.has_next}
        class={cn(
          "rounded-lg border border-hive-border px-4 py-2 text-sm font-medium hover:bg-hive-muted transition-colors",
          !props.has_next &&
            "opacity-50 cursor-not-allowed hover:bg-transparent",
        )}
      >
        Next Page
      </button>
    </div>
  );
};

// ---------------------------------------------------------------------------
// HivePostList
// ---------------------------------------------------------------------------

export const HivePostList: Component<HivePostListProps> = (props) => {
  const variant = () => props.variant ?? "compact";
  const hide = () => props.hide ?? [];
  const link_target = () =>
    props.linkTarget ?? "https://blog.openhive.network";

  const hook_options: UseHivePostListOptions = {
    sort: props.sort,
    tag: props.tag,
    limit: props.limit,
  };

  const {
    posts,
    is_loading,
    error,
    sort,
    set_sort,
    has_next,
    has_prev,
    next_page,
    prev_page,
    page,
  } = useHivePostList(hook_options);

  const has_pinned = () =>
    props.pinned_posts !== undefined && props.pinned_posts.length > 0;

  return (
    <div class={cn("w-full", props.class)}>
      <Show when={props.show_sort_controls}>
        <SortControls sort={sort()} on_change={set_sort} />
      </Show>

      <Show when={has_pinned()}>
        <div class="mb-4 pb-4 border-b border-hive-border">
          <p class="text-xs font-medium text-hive-muted-foreground uppercase tracking-wide mb-2">
            Pinned
          </p>
          <div class="flex flex-col gap-2">
            <For each={props.pinned_posts ?? []}>
              {(pin) => (
                <PinnedPostItem
                  author={pin.author}
                  permlink={pin.permlink}
                  hide={hide()}
                  link_target={link_target()}
                />
              )}
            </For>
          </div>
        </div>
      </Show>

      <Show when={is_loading()}>
        <LoadingSkeleton variant={variant()} count={4} />
      </Show>

      <Show when={!is_loading() && error()}>
        <div class="rounded-lg border border-hive-border p-4">
          <p class="text-sm text-hive-muted-foreground">
            {error()?.message}
          </p>
        </div>
      </Show>

      <Show when={!is_loading() && !error() && posts().length === 0}>
        <p class="text-sm text-hive-muted-foreground py-8 text-center">
          No posts found
        </p>
      </Show>

      <Show when={!is_loading() && !error() && posts().length > 0}>
        <Show
          when={variant() !== "grid"}
          fallback={
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              <For each={posts()}>
                {(post) => (
                  <PostItem
                    post={post}
                    variant={variant()}
                    hide={hide()}
                    link_target={link_target()}
                  />
                )}
              </For>
            </div>
          }
        >
          <div
            class={cn(
              "flex flex-col",
              variant() === "compact" ? "gap-2" : "gap-4",
            )}
          >
            <For each={posts()}>
              {(post) => (
                <PostItem
                  post={post}
                  variant={variant()}
                  hide={hide()}
                  link_target={link_target()}
                />
              )}
            </For>
          </div>
        </Show>
        <PaginationControls
          page={page()}
          has_prev={has_prev()}
          has_next={has_next()}
          on_prev={prev_page}
          on_next={next_page}
        />
      </Show>
    </div>
  );
};
