// packages/solid/src/api-tracker.tsx
import { createSignal, Show, For, type Component } from "solid-js";
import { Popover } from "@kobalte/core/popover";
import { useHive } from "./hive-provider";
import type { ConnectionStatus } from "@kkocot/honeycomb-core";

export interface ApiTrackerProps {
  class?: string;
  showUrl?: boolean;
  side?: "top" | "bottom";
}

const get_status_color = (s: ConnectionStatus): string => {
  switch (s) {
    case "connected":
      return "bg-green-500";
    case "connecting":
    case "reconnecting":
      return "bg-yellow-500 animate-pulse";
    case "error":
    case "disconnected":
      return "bg-red-500";
    default:
      return "bg-gray-500";
  }
};

const format_url = (url: string): string => {
  try {
    return new URL(url).hostname;
  } catch {
    return url;
  }
};

const format_time = (timestamp: number | null): string => {
  if (timestamp === null) return "Never";
  return new Date(timestamp).toLocaleTimeString();
};

export const ApiTracker: Component<ApiTrackerProps> = (props) => {
  const hive = useHive();
  const [is_refreshing, set_is_refreshing] = createSignal(false);

  const handle_open_change = async (open: boolean) => {
    if (open) {
      set_is_refreshing(true);
      try {
        await hive.refreshEndpoints();
      } finally {
        set_is_refreshing(false);
      }
    }
  };

  const handle_refresh = async () => {
    set_is_refreshing(true);
    try {
      await hive.refreshEndpoints();
    } finally {
      set_is_refreshing(false);
    }
  };

  const current_endpoint = () => {
    const endpoint = hive.apiEndpoint();
    if (!endpoint) return null;
    return props.showUrl ? format_url(endpoint) : null;
  };

  const healthy_count = () =>
    hive.endpoints().filter((ep) => ep.healthy).length;

  return (
    <Popover
      placement={props.side === "top" ? "top" : "bottom"}
      onOpenChange={handle_open_change}
    >
      <Popover.Trigger
        class={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-border bg-card cursor-pointer hover:bg-muted/50 transition-colors ${props.class || ""}`}
      >
        <div
          classList={{
            "w-2.5 h-2.5 rounded-full": true,
            [get_status_color(hive.status())]: true,
          }}
        />

        <span class="text-sm text-foreground capitalize">{hive.status()}</span>

        <Show when={current_endpoint()}>
          <span class="text-xs text-muted-foreground font-mono truncate max-w-[200px]">
            {current_endpoint()}
          </span>
        </Show>
      </Popover.Trigger>

      <Popover.Portal>
        <Popover.Content class="z-50 w-80 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none data-[expanded]:animate-in data-[expanded]:fade-in-0 data-[expanded]:zoom-in-95">
          <div class="flex items-center justify-between mb-3">
            <div>
              <h3 class="text-sm font-semibold">API Endpoints</h3>
              <p class="text-xs text-muted-foreground">
                {healthy_count()}/{hive.endpoints().length} healthy
              </p>
            </div>
            <button
              type="button"
              onClick={handle_refresh}
              disabled={is_refreshing()}
              class="text-xs text-muted-foreground hover:text-foreground disabled:opacity-50 cursor-pointer"
            >
              <Show when={is_refreshing()} fallback="Refresh">
                Checking...
              </Show>
            </button>
          </div>

          <div class="space-y-0">
            <For each={hive.endpoints()}>
              {(endpoint) => (
                <div class="flex items-start justify-between gap-2 py-2 border-b border-border last:border-0">
                  <div class="flex items-start gap-2 flex-1 min-w-0">
                    <div
                      classList={{
                        "w-2 h-2 rounded-full mt-1": true,
                        "bg-green-500": endpoint.healthy,
                        "bg-red-500": !endpoint.healthy,
                      }}
                    />
                    <div class="flex-1 min-w-0">
                      <div class="text-xs font-mono truncate">
                        {format_url(endpoint.url)}
                      </div>
                      <p class="text-xs text-muted-foreground mt-0.5">
                        Last check: {format_time(endpoint.lastCheck)}
                      </p>
                      <Show when={endpoint.lastError}>
                        <p class="text-xs text-red-500 mt-0.5 truncate">
                          {endpoint.lastError}
                        </p>
                      </Show>
                    </div>
                  </div>
                  <span
                    classList={{
                      "text-xs px-2 py-0.5 rounded shrink-0": true,
                      "bg-green-500/10 text-green-500": endpoint.healthy,
                      "bg-red-500/10 text-red-500": !endpoint.healthy,
                    }}
                  >
                    {endpoint.healthy ? "Healthy" : "Unhealthy"}
                  </span>
                </div>
              )}
            </For>
            <Show when={hive.endpoints().length === 0}>
              <p class="text-xs text-muted-foreground text-center py-4">
                No endpoints configured
              </p>
            </Show>
          </div>
        </Popover.Content>
      </Popover.Portal>
    </Popover>
  );
};

// apps/docs/app/(docs)/components/api-tracker/page.tsx
import Link from "next/link";
import { ArrowLeft, ArrowRight, Info } from "lucide-react";
import { CodeBlock } from "@/components/code-block";

const CODE = {
  react: `import { ApiTracker } from "@kkocot/honeycomb-react";

function App() {
  return (
    <div>
      <ApiTracker />
    </div>
  );
}`,
  reactShowUrl: `<ApiTracker showUrl side="bottom" />`,
  solid: `import { ApiTracker } from "@kkocot/honeycomb-solid";

function App() {
  return (
    <div>
      <ApiTracker />
    </div>
  );
}`,
  vue: `<template>
  <div>
    <ApiTracker />
  </div>
</template>

<script setup lang="ts">
import { ApiTracker } from "@kkocot/honeycomb-vue";
</script>`,
  vueProps: `<ApiTracker :show-url="true" side="bottom" />`,
};

export default async function ApiTrackerPage() {
  return (
    <article className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">ApiTracker</h1>
        <p className="mt-2 text-lg text-muted-foreground">
          Displays current API connection status with an expandable tooltip
          showing all endpoint health details.
        </p>
      </div>

      {/* Info */}
      <section className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4">
        <div className="flex gap-3">
          <Info className="h-5 w-5 text-blue-500 shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-blue-500">Health Monitoring</p>
            <p className="mt-1 text-sm text-muted-foreground">
              ApiTracker automatically refreshes endpoint health when the
              tooltip is opened. You can also trigger a manual refresh from
              inside the tooltip.
            </p>
          </div>
        </div>
      </section>

      {/* Features */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Features</h2>
        <ul className="space-y-2 text-muted-foreground">
          <li className="flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500 mt-2 shrink-0" />
            Compact pill badge showing connection status (green/yellow/red)
          </li>
          <li className="flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500 mt-2 shrink-0" />
            Click to expand tooltip with all endpoints and health status
          </li>
          <li className="flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500 mt-2 shrink-0" />
            Auto-refresh on open + manual refresh button
          </li>
          <li className="flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500 mt-2 shrink-0" />
            Health badges (Healthy/Unhealthy) and last check timestamps
          </li>
          <li className="flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500 mt-2 shrink-0" />
            Click outside to dismiss tooltip
          </li>
        </ul>
      </section>

      {/* Usage */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Usage</h2>
        <div className="space-y-6">
          <div>
            <h3 className="text-sm font-medium mb-2">React</h3>
            <CodeBlock code={CODE.react} language="tsx" />
          </div>
          <div>
            <h3 className="text-sm font-medium mb-2">Solid.js</h3>
            <CodeBlock code={CODE.solid} language="tsx" />
          </div>
          <div>
            <h3 className="text-sm font-medium mb-2">Vue 3</h3>
            <CodeBlock code={CODE.vue} language="vue" />
          </div>
        </div>
      </section>

      {/* Props */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Props</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="py-3 px-4 text-left font-semibold">Prop</th>
                <th className="py-3 px-4 text-left font-semibold">Type</th>
                <th className="py-3 px-4 text-left font-semibold">Default</th>
                <th className="py-3 px-4 text-left font-semibold">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              <tr>
                <td className="py-3 px-4">
                  <code>className</code> / <code>class</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>string</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">-</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Additional CSS classes for the container
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>showUrl</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>boolean</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>false</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Show current endpoint hostname in the pill badge
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4">
                  <code>side</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>&quot;top&quot; | &quot;bottom&quot;</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  <code>&quot;bottom&quot;</code>
                </td>
                <td className="py-3 px-4 text-muted-foreground">
                  Popover opens above or below the pill
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* With URL Example */}
      <section>
        <h2 className="text-xl font-semibold mb-4">Examples</h2>
        <div className="space-y-6">
          <div>
            <h3 className="text-sm font-medium mb-2">
              Show endpoint URL in pill (React)
            </h3>
            <CodeBlock code={CODE.reactShowUrl} language="tsx" />
          </div>
          <div>
            <h3 className="text-sm font-medium mb-2">
              Vue prop syntax
            </h3>
            <CodeBlock code={CODE.vueProps} language="vue" />
          </div>
        </div>
      </section>

      {/* Navigation */}
      <section className="flex items-center justify-between">
        <Link
          href="/theming"
          className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-medium transition-colors hover:bg-accent"
        >
          <ArrowLeft className="h-4 w-4" />
          Theming
        </Link>
        <Link
          href="/components/avatar"
          className="inline-flex items-center gap-2 rounded-lg bg-hive-red px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-hive-red/90"
        >
          Avatar
          <ArrowRight className="h-4 w-4" />
        </Link>
      </section>
    </article>
  );
}
