// apps/demo-vue/src/components/PostCardTab.vue
<template>
  <div class="space-y-6">
    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Card Variant</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Default card with author avatar, title, content preview, and stats.
      </p>
      <div class="max-w-lg space-y-4">
        <HivePostCard
          author="barddev"
          permlink="my-honey-pot"
        />
        <HivePostCard
          :author="GTG_POST_A.author"
          :permlink="GTG_POST_A.permlink"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Compact Variant</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Inline row with thumbnail, title, and stats. Suitable for lists.
      </p>
      <div class="space-y-3 max-w-lg">
        <HivePostCard
          v-for="post in DEMO_POSTS"
          :key="post.permlink"
          :author="post.author"
          :permlink="post.permlink"
          variant="compact"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Grid Variant</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Card optimized for grid layouts with prominent thumbnail.
      </p>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <HivePostCard
          v-for="post in DEMO_POSTS"
          :key="post.permlink"
          :author="post.author"
          :permlink="post.permlink"
          variant="grid"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Hidden Elements</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Use the hide prop to selectively remove author info and thumbnail.
      </p>
      <div class="max-w-lg">
        <HivePostCard
          author="barddev"
          permlink="my-honey-pot"
          :hide="['author', 'thumbnail']"
        />
      </div>
    </section>

    <section class="border border-border rounded-lg p-6 bg-muted/20">
      <h2 class="text-2xl font-semibold mb-4">Custom Link Target</h2>
      <p class="text-sm text-muted-foreground mb-4">
        Override the default link base URL with linkTarget prop. Links will
        point to PeakD instead of the default OpenHive blog.
      </p>
      <div class="max-w-lg">
        <HivePostCard
          author="blocktrades"
          permlink="updates-for-hive-roadmap-from-the-blocktrades-team"
          link-target="https://peakd.com"
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { HivePostCard } from "@barddev/honeycomb-vue";

const GTG_POST_A = {
  author: "gtg",
  permlink: "hive-hardfork-28-jump-starter-kit",
};
const GTG_POST_B = {
  author: "gtg",
  permlink: "brace-yourself-hardfork-is-coming",
};

const DEMO_POSTS = [
  { author: "barddev", permlink: "my-honey-pot" },
  {
    author: "blocktrades",
    permlink: "updates-for-hive-roadmap-from-the-blocktrades-team",
  },
  GTG_POST_A,
  GTG_POST_B,
];
</script>

// apps/demo-svelte-astro/src/components/PostCardTab.svelte
<script lang="ts">
  import { HivePostCard } from "@barddev/honeycomb-svelte";
  import type { PostHideOption } from "@barddev/honeycomb-svelte";

  const POST_A = { author: "barddev", permlink: "my-honey-pot" };
  const POST_B = {
    author: "blocktrades",
    permlink: "updates-for-hive-roadmap-from-the-blocktrades-team",
  };
  const POST_C = {
    author: "gtg",
    permlink: "hive-hardfork-28-jump-starter-kit",
  };
  const POST_D = {
    author: "gtg",
    permlink: "brace-yourself-hardfork-is-coming",
  };

  const HIDDEN_ELEMENTS: PostHideOption[] = ["payout", "votes"];
</script>

<div class="space-y-6">
  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Card Variant</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Default full card with thumbnail, author, title, body preview, and stats.
    </p>
    <div class="max-w-lg space-y-4">
      <HivePostCard author={POST_A.author} permlink={POST_A.permlink} />
      <HivePostCard author={POST_C.author} permlink={POST_C.permlink} />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Compact Variant</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Inline layout with small thumbnail, title, and stats. Good for lists and
      sidebars.
    </p>
    <div class="max-w-lg space-y-3">
      <HivePostCard
        author={POST_A.author}
        permlink={POST_A.permlink}
        variant="compact"
      />
      <HivePostCard
        author={POST_B.author}
        permlink={POST_B.permlink}
        variant="compact"
      />
      <HivePostCard
        author={POST_C.author}
        permlink={POST_C.permlink}
        variant="compact"
      />
      <HivePostCard
        author={POST_D.author}
        permlink={POST_D.permlink}
        variant="compact"
      />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Grid Variant</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Image-first layout designed for grid displays and content feeds.
    </p>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <HivePostCard
        author={POST_A.author}
        permlink={POST_A.permlink}
        variant="grid"
      />
      <HivePostCard
        author={POST_B.author}
        permlink={POST_B.permlink}
        variant="grid"
      />
      <HivePostCard
        author={POST_C.author}
        permlink={POST_C.permlink}
        variant="grid"
      />
      <HivePostCard
        author={POST_D.author}
        permlink={POST_D.permlink}
        variant="grid"
      />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Hidden Elements</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Use the <code class="text-xs bg-muted px-1 py-0.5 rounded">hide</code>
      prop to selectively remove payout, votes, comments, author, thumbnail, or time.
    </p>
    <div class="max-w-lg">
      <HivePostCard
        author={POST_A.author}
        permlink={POST_A.permlink}
        hide={HIDDEN_ELEMENTS}
      />
    </div>
  </section>

  <section class="border border-border rounded-lg p-6 bg-muted/20">
    <h2 class="text-2xl font-semibold mb-4">Custom Link Target</h2>
    <p class="text-sm text-muted-foreground mb-4">
      Override the default link base URL with
      <code class="text-xs bg-muted px-1 py-0.5 rounded">linkTarget</code>.
      Links below point to peakd.com.
    </p>
    <div class="max-w-lg">
      <HivePostCard
        author={POST_B.author}
        permlink={POST_B.permlink}
        linkTarget="https://peakd.com"
      />
    </div>
  </section>
</div>
